### ISSUE TITLE
Research how Chat can be implemented with React

### ISSUE THREAD

**Issue by timo1227** [timo1227/covey.town#8]

**Comment by nilmo-contreras** [comment]
# Implementing Chat Using React

## Using a backend solution

There are many ways to implement chat in a website using react. The most common approach is the following:
1. Choose a backend chat solution: You can choose from a number of backend chat solutions, such as Firebase, PubNub, or Pusher. These services provide APIs and SDKs that make it easy to add real-time chat functionality.
2. Create a React component for the chat interface: a chat interface allows users to send and receive messages. This can be achieved using React components that render the chat UI.
3. Connect to the backend chat service: connecting to the backend chat service requires using its API or SDK. This enables the React application to send and receive messages in real-time.
4. Manage the chat state: managing the chat state in your React applications is required. This includes storing the chat messages and updating the UI when new messages are received.
5. This last step is optional, but it brings chat alive. Implement features like typing indicators, message read receipts, and push notifications.

## Without a backend solution

Not using a backend solution has its drawbacks, but it can still be done. 
1. Design and build react components that will display the chat user interface. The user interface allows a user to send and receive messages. 
2. Manage chate states. This involves handling and updating the data that comprises the chat, such as storing chat messages and updating the chat user interface whenever new messages are received or sent.
